version: '3.3'

services:
  api:
    build: .
    image: itcrowd
    environment:
      DATABASE_URL: '${DATABASE_URL}'
      NODE_ENV: '${NODE_ENV}'
      JWT_SEED: '${JWT_SEED}'
      JWT_EXPIRES_IN: '${JWT_EXPIRES_IN}'
    ports:
      - '8080:8080'
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: root
