/people/{id}/aliases:
  post:
    tags: 
      - Person
    summary:  Adds an alias to a person
    description: Adds an alias to a person
    produces:
      - application/json
    parameters:
    - name: Authorization
      in: header
      description: Authorization token
      required: true
      type: string
      example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiaWQiOjF9LCJpYXQiOjE1MTAxNTI2MDEsImV4cCI6MTUxMDIzOTAwMX0.5JmvBOkG3jkhQfZwB61o650P0XDqIijuRv41m6Sn6Qk
    - name: id
      in: path
      description: Person id
      required: true
      type: integer
      example: 1
    - name: body
      in: body
      required: true
      schema:
        type: object
        required:
          - alias
        properties:
          alias:
            type: string
            example: The Rock
            description: alias
            minLength: 1
    responses:
      201:
        description: Ok
        headers:
          Location:
            description: Created alias uri
            type: string
            format: uri
            example: http://localhost:8080/rest/people/1/aliases/1
        schema:
          type: object
          required:
            - _links
          properties:
            _links:
              type: object
              required:
                - self
              properties:
                self:
                  type: object
                  required:
                    - href
                  properties:
                    href:
                      type: string
                      format: uri
                      example: http://localhost:8080/rest/people/1/aliases/1
      404:
        description: Not found
      500:
        description: Internal server error
