/people:
  get:
    tags: 
      - Person
    summary:  Return all the people
    description: Return all the people including movies in the different roles the Person has
    produces:
      - application/json
    responses:
      200:
        description: Ok
        schema:
          type: object
          required:
            - items
          properties:
            items:
              type: array
              items:
                type: object
                properties:
                  firstName:
                    type: string
                    example: Sylvester
                  lastName:
                    type: string
                    example: Stallone
                  _links:
                    type: object
                    required:
                      - self
                      - aliases
                      - moviesAsActor
                      - moviesAsDirector
                      - moviesAsProducer
                    properties:
                      self:
                        type: object
                        required:
                          - href
                        properties:
                          href:
                            type: string
                            format: uri
                            example: http://localhost:8080/rest/people/1
                      aliases:
                        type: object
                        required:
                          - href
                        properties:
                          href:
                            type: string
                            format: uri
                            example: http://localhost:8080/rest/people/1/aliases
                      moviesAsActor:
                        type: object
                        required:
                          - href
                        properties:
                          href:
                            type: string
                            format: uri
                            example: http://localhost:8080/rest/movies?actorId=1
                      moviesAsDirector:
                        type: object
                        required:
                          - href
                        properties:
                          href:
                            type: string
                            format: uri
                            example: http://localhost:8080/rest/movies?directorId=1
                      moviesAsProducer:
                        type: object
                        required:
                          - href
                        properties:
                          href:
                            type: string
                            format: uri
                            example: http://localhost:8080/rest/movies?producerId=1
      500:
        description: Internal server error
