/users:
  post:
    tags: 
      - User
    summary:  Creates a new user
    description: Creates a new user
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
    - name: body
      in: body
      required: true
      schema:
        type: object
        required:
          - email
          - password
        properties:
          email:
            type: string
            example: some@email.com
            description: User's email
            format: email
          password:
            type: string
            example: secret
            description: User's password
    responses:
      201:
        description: Created
        schema:
          type: object
          required:
            - _links
          properties:
            _links:
              type: object
              required:
                - login
              properties:
                login:
                  type: object
                  required:
                    - href
                  properties:
                    href:
                      type: string
                      format: uri
                      example: http://localhost:8080/rest/users/login
      400:
        description: Bad Request
      500:
        description: Internal server error
