/people/{personId}/aliases/{aliasId}:
  delete:
    tags: 
      - Person
    summary:  Removes an alias from a person
    description: Removes an alias from a person
    produces:
      - application/json
    parameters:
    - name: Authorization
      in: header
      description: Authorization token
      required: true
      type: string
      example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiaWQiOjF9LCJpYXQiOjE1MTAxNTI2MDEsImV4cCI6MTUxMDIzOTAwMX0.5JmvBOkG3jkhQfZwB61o650P0XDqIijuRv41m6Sn6Qk
    - name: personId
      in: path
      description: Person id
      required: true
      type: integer
      example: 1
    - name: aliasId
      in: path
      description: alias id
      required: true
      type: integer
      example: 1
    responses:
      204:
        description: No content
      404:
        description: Not found
      500:
        description: Internal server error
